# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6P654Iw1xAAl-4gudoU4Sw0-LGxhr1g
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import tempfile, os, nltk
# from langchain_community.document_loaders import PyPDFLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.vectorstores import Chroma
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_core.prompts import PromptTemplate
# from langchain_core.runnables import RunnablePassthrough
# from langchain_core.output_parsers import StrOutputParser
# from langchain_groq import ChatGroq
# 
# os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]
# 
# st.set_page_config(page_title="PDF Chatbot", page_icon="📄")
# st.title("📄 PDF Chatbot")
# st.caption("Upload any PDF and ask questions in any language")
# 
# @st.cache_resource
# def get_embeddings():
#     return HuggingFaceEmbeddings(
#         model_name="sentence-transformers/all-MiniLM-L6-v2"
#     )
# 
# def build_chain(pdf_path):
#     loader = PyPDFLoader(pdf_path)
#     chunks = RecursiveCharacterTextSplitter(
#         chunk_size=500, chunk_overlap=50
#     ).split_documents(loader.load())
# 
#     vectorstore = Chroma.from_documents(chunks, get_embeddings())
# 
#     prompt = PromptTemplate.from_template("""
# Use the context below to answer the question.
# Answer in the same language as the question.
# If the answer is not in the document, say "This information is not available in the document."
# 
# Context: {context}
# Question: {question}
# Answer:""")
# 
#     def format_docs(docs):
#         return "\n\n".join(d.page_content for d in docs)
# 
#     return (
#         {"context": vectorstore.as_retriever(search_kwargs={"k": 3}) | format_docs,
#          "question": RunnablePassthrough()}
#         | prompt
#         | ChatGroq(model="llama-3.1-8b-instant", temperature=0)
#         | StrOutputParser()
#     )
# 
# # Upload PDF
# uploaded_file = st.file_uploader("Upload your PDF", type="pdf")
# 
# if uploaded_file:
#     with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as f:
#         f.write(uploaded_file.read())
#         tmp_path = f.name
# 
#     with st.spinner("Reading PDF..."):
#         chain = build_chain(tmp_path)
# 
#     st.success("Ready! Ask any question 👇")
# 
#     if "messages" not in st.session_state:
#         st.session_state.messages = []
# 
#     for msg in st.session_state.messages:
#         with st.chat_message(msg["role"]):
#             st.write(msg["content"])
# 
#     if question := st.chat_input("Ask your question here..."):
#         st.session_state.messages.append({"role": "user", "content": question})
#         with st.chat_message("user"):
#             st.write(question)
# 
#         with st.chat_message("assistant"):
#             with st.spinner("Thinking..."):
#                 answer = chain.invoke(question)
#             st.write(answer)
# 
#         st.session_state.messages.append({"role": "assistant", "content": answer})